---
title: "Proficiency-Test-II"
author: "Alex Zhang"
format: html
editor: visual
---

## Task-1

```{r}
for(i in 1:3){
  print(mtcars$mpg[i])
}
```

## Task-2

```{r}
count_above <- function(vector, cutoff){
  # create a function named count_above with two inputs: the numeric vector and the cutoff value.
  count <- 0
  # initialize and set the value of count to 0.
  for(i in 1:length(vector)){
  # check every elements in the given vector.
    if(vector[i] > cutoff){
    # check if the element is larger than the cutoff value.
      count <- count + 1
      # if it satisfied the condition, count this element into count variable.
    }
  }
  return(count)
  # return the value of the observations.
}
mtcars
```

```{r}
count_above(iris$Sepal.Length, 6)
```

```{r}
count_above(mtcars$disp, 149.9)
```

## Task-3

Data masking allows you to refer to variables in the "current" data frame (usually supplied in the .data argument), without any other prefix. 

## Task-4

```{r}
iris$Sepal.Length[1]
iris[1, 1]
```
It returns the first iris flower's sepal length.